/* Ellipsis, made by me 😜  https://github.com/zamkevich */
import{tick as A}from"svelte";const W=`
  position:absolute;
  left:0;
  top:-100%;
  border:none;
  opacity:0;
  visibility:hidden;
  pointer-events:none;`;function R(i,{cutLength:z=0,overflowBadge:w="\u2026",affectNode:l=null,sliceAfter:N=/\p{Letter}/u}={}){let n,t,H=0,c=!0,j=l?l.style.display:null,d=!1,a=new ResizeObserver(L),C=new MutationObserver(D),S=e=>new CustomEvent("update",{detail:e}),s=window.__ellipsisNodesContainer;function T(){s||(s=document.createElement("div"),s.setAttribute("ariaHidden",!0),s.setAttribute("id","ellipsisNodesContainer"),s.style.cssText=W,document.body.append(s),window.__ellipsisNodesContainer=s)}p();async function p(){await m()?(T(),_(),k(),g()):(u(),O())}function _(){let e=i.cloneNode(!0);e.style.position="unset",typeof t=="object"?(t.before(e),t.remove(),t=e):(t=e,i.before(t),s.append(i),O())}function k(){typeof n=="object"&&n.remove(),n=i.cloneNode(!0),s.append(n)}async function f(e,o){await A(),i.dispatchEvent(S({type:e,status:o}))}function h(e){e=="hide"&&(l.style.display="none",d=!0),e=="show"&&(l.style.display=j,d=!1)}async function m(){let e;return typeof t=="object"?(e=t,t.textContent=i.textContent):e=i,d&&h("show"),e.clientHeight<e.scrollHeight?l?(h("hide"),e.clientHeight<e.scrollHeight?(h("show"),f("overflow",!0),!0):(f("overflow",!1),!1)):(f("overflow",!0),!0):(f("overflow",!1),!1)}function E(){return n.textContent="Lg",t.clientHeight>=n.clientHeight}function g(){if(E()){let e=t.clientHeight/(t.scrollHeight/100),o=t.style.width;t.style.width="100%",n.style.width=t.clientWidth-1+"px",t.style.width=o,b(Math.round(i.textContent.length/100*e))}else u()}function b(e,o,r=!1){if(r=r||++H,r!=H)return;let M=i.textContent.substr(0,e)+w;n.textContent=M,n.clientHeight>t.clientHeight&&(o==!1?x(--e):setTimeout(()=>b(--e,!0,r),20)),n.clientHeight<=t.clientHeight&&(o==!0?x(e):b(++e,!1,r))}function x(e){for(;!N.test(i.textContent[e-1]);)--e;t.textContent=i.textContent.substr(0,e-z)+w,u()}function O(){C.observe(i,{attributes:!0,characterData:!0,subtree:!0})}function u(){c=!0,a.observe(typeof t=="object"?t:i)}let y=!1;function D(){y||(y=!0,setTimeout(()=>{a.disconnect(),p(),y=!1},300))}let v=!1;function L(){c?c=!1:v||(v=!0,setTimeout(async()=>{typeof t=="object"?(a.disconnect(),await m()?g():u()):p(),v=!1},300))}return{update(e){e.affectNode&&(l=e.affectNode)},destroy(){a.disconnect(),C.disconnect()}}}export{R as default};
