name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      # Build
      - run: npm install --global yarn
      - run: yarn install
      - run: yarn build
      # Setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.DEV_KEY }}" > "$HOME/.ssh/rodshtein"
      - run: chmod 600 "$HOME/.ssh/rodshtein"
      # Deploy bild
      - run: rsync -e "ssh -i $HOME/.ssh/rodshtein -o StrictHostKeyChecking=no" --exclude-from=".rsyncignore" --archive --compress --delete . admin@81.163.26.40:/var/www/allasia/front
      #  restart app
      - name: restart app
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd /var/www/allasia/front
            yarn install
            pm2 restart Allasia_Front
          host: 81.163.26.40
          username: admin
          privateKey: ${{ secrets.DEV_KEY }}